name: avdasymirb

topology:
  kinds:
    ceos:
      image: "${HARBOR_HOST}/external/ceos-image:4.29.0.2F"
      exec:
        - sleep 10
        - FastCli -p 15 -c 'security pki key generate rsa 4096 eAPI.key'
        - FastCli -p 15 -c 'security pki certificate generate self-signed eAPI.crt key eAPI.key generate rsa 4096 validity 30000 parameters common-name eAPI'
    linux:
      image: "${HARBOR_HOST}/external/alpine-host:v3.1.1"
  nodes:
    atl-client1:
      kind: linux
      mgmt_ipv4: 172.20.20.17
      env:
        TMODE: lacp
    atl-client2:
      kind: linux
      mgmt_ipv4: 172.20.20.18
      env:
        TMODE: lacp
    atl-leaf1:
      kind: eos
      mgmt_ipv4: 172.20.20.19
      startup-config: configs/startup/atl-leaf1.cfg
    atl-leaf2:
      kind: eos
      mgmt_ipv4: 172.20.20.20
      startup-config: configs/startup/atl-leaf2.cfg
    atl-leaf3:
      kind: eos
      mgmt_ipv4: 172.20.20.21
      startup-config: configs/startup/atl-leaf3.cfg
    atl-leaf4:
      kind: eos
      mgmt_ipv4: 172.20.20.22
      startup-config: configs/startup/atl-leaf4.cfg
    atl-spine1:
      kind: eos
      mgmt_ipv4: 172.20.20.23
      startup-config: configs/startup/atl-spine1.cfg
    atl-spine2:
      kind: eos
      mgmt_ipv4: 172.20.20.24
      startup-config: configs/startup/atl-spine2.cfg

  links:
    - endpoints: ["atl-leaf1:eth3", "atl-spine1:eth3"]
    - endpoints: ["atl-leaf2:eth3", "atl-spine1:eth4"]
    - endpoints: ["atl-leaf3:eth3", "atl-spine1:eth5"]
    - endpoints: ["atl-leaf4:eth3", "atl-spine1:eth6"]
    - endpoints: ["atl-leaf1:eth4", "atl-spine2:eth3"]
    - endpoints: ["atl-leaf2:eth4", "atl-spine2:eth4"]
    - endpoints: ["atl-leaf3:eth4", "atl-spine2:eth5"]
    - endpoints: ["atl-leaf4:eth4", "atl-spine2:eth6"]
    - endpoints: ["atl-leaf1:eth5", "atl-client1:eth1"]
    - endpoints: ["atl-leaf4:eth5", "atl-client2:eth1"]

mgmt:
  network: ceos_clab                
  ipv4_subnet: 172.100.100.0/24       
  ipv6_subnet: 2001:172:100:100::/80
