---
jinja2_transforms:
  - name: "device_cisco"
    description: "Template to generate startup configuration for Cisco devices"
    query: "device_info"
    template_path: "templates/device_cisco_config.tpl.j2"

  - name: "device_arista"
    description: "Template to generate startup configuration for Arista devices"
    query: "device_info"
    template_path: "templates/device_arista_config.tpl.j2"

  # - name: "clab_topology"
  #   query: "topology_info"
  #   template_path: "topology/topology.tpl.j2"

artifact_definitions:
  - name: "Openconfig Interface for Arista devices"
    artifact_name: "openconfig-interfaces"
    parameters:
      device: "name__value"
    content_type: "application/json"
    targets: "arista_devices"
    transformation: "OCInterfaces"

  - name: "Startup Config for Cisco devices"
    artifact_name: "startup-config"
    parameters:
      device: "name__value"
    content_type: "text/plain"
    targets: "cisco_devices"
    transformation: "device_cisco"

  - name: "Startup Config for Arista devices"
    artifact_name: "startup-config"
    parameters:
      device: "name__value"
    content_type: "text/plain"
    targets: "arista_devices"
    transformation: "device_arista"

check_definitions:
  - name: "check_device_topology"
    class_name: "InfrahubCheckDeviceTopology"
    file_path: "checks/check_device_topology.py"

python_transforms:
  - name: OCInterfaces
    class_name: OCInterfaces
    file_path: "transforms/openconfig.py"
