---
rfiles:
  - name: device_startup
    description: "Template to generate OSPF iBGP config for network devices"
    query: "device_startup_query"
    repository: "self"
    template_path: "templates/device_startup_config.j2"

  - name: device_startup_isis
    description: "Template to generate ISIS iBGP config for network devices"
    query: "device_startup_query"
    repository: "self"
    template_path: "templates/device_startup_config_isis.j2"

  - name: clab_topology
    description: "Template to generate clab device topology"
    query: "topology_info_query"
    repository: "self"
    template_path: "templates/clab_topology.j2"

artifact_definitions:
  - name: "Startup Config for arista devices"
    artifact_name: "startup-config"
    parameters:
      device: "name__value"
    content_type: "text/plain"
    targets: "arista_devices"
    transformation: "device_startup"

  - name: "Startup Config isis for arista devices"
    artifact_name: "startup-config-isis"
    parameters:
      device: "name__value"
    content_type: "text/plain"
    targets: "arista_devices"
    transformation: "device_startup_isis"

  # - name: "Clab topology"
  #   artifact_name: "startup-config"
  #   parameters:
  #     device: "name__value"
  #   content_type: "text/plain"
  #   targets: "arista_devices"
  #   transformation: "clab_topology"
