---
# Default state for all rules
default: true

# MD003/heading-style - Heading style
MD003:
  style: "atx"

# MD004/ul-style - Unordered list style
MD004:
  style: "dash"

# MD007/ul-indent - Unordered list indentation
MD007:
  indent: 2

# MD013/line-length - Line length
MD013: false

# MD024/no-duplicate-heading - Multiple headings with the same content
MD024:
  siblings_only: true

# MD033/no-inline-html - Inline HTML
MD033: false

# MD041/first-line-heading - First line in a file should be a top-level heading
MD041: false

# MD046/code-block-style - Code block style
MD046:
  style: "fenced"

# MD048/code-fence-style - Code fence style
MD048:
  style: "backtick"
