---
version: "3.4"

services:
  message-queue:
    image: "${MESSAGE_QUEUE_DOCKER_IMAGE:-rabbitmq:latest}"
    environment:
      - "RABBITMQ_DEFAULT_USER=infrahub"
      - "RABBITMQ_DEFAULT_PASS=infrahub"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 30s
      retries: 3

  cache:
    image: "${CACHE_DOCKER_IMAGE:-redis:latest}"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 3

  database:
    image: "${DATABASE_DOCKER_IMAGE:-neo4j:community}"
    environment:
      - "NEO4J_AUTH=neo4j/admin"
      - "NEO4J_dbms_security_procedures_unrestricted=apoc.*"
      - "NEO4J_dbms_security_auth__minimum__password__length=4"
    volumes:
      - "./plugins:/plugins"
      - "database_data:/data"
      - "database_logs:/logs"
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 2s
      timeout: 10s
      retries: 20
      start_period: 3s

  infrahub-server:
    image: "${INFRAHUB_DOCKER_IMAGE}"
    command: gunicorn --config backend/infrahub/serve/gunicorn_config.py --logger-class infrahub.serve.log.GunicornLogger infrahub.server:app
    depends_on:
      database:
        condition: service_healthy
      message-queue:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      - "INFRAHUB_CONFIG=/source/development/infrahub.toml"
      - "INFRAHUB_PRODUCTION=false"
      - "INFRAHUB_LOG_LEVEL=INFO"
      - "INFRAHUB_SECURITY_INITIAL_ADMIN_TOKEN=${INFRAHUB_SDK_API_TOKEN}"
      - "INFRAHUB_SECURITY_SECRET_KEY=${INFRAHUB_SECURITY_SECRET_KEY}"
      - "INFRAHUB_ALLOW_ANONYMOUS_ACCESS=true"
      - "PROMETHEUS_MULTIPROC_DIR=/prom_shared"
      - "INFRAHUB_FRONTEND_DIRECTORY=/opt/infrahub/frontend"
      - "INFRAHUB_DB_TYPE=neo4j"
    ports:
      - "8000:8000"
    volumes:
      - "storage_data:/opt/infrahub/storage"
      - "../models:/tmp/models"
    tty: true
    healthcheck:
      test: wget -O /dev/null http://localhost:8000/api/schema || exit 1
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  infrahub-git:
    deploy:
      mode: replicated
      replicas: 2
    image: "${INFRAHUB_DOCKER_IMAGE}"
    command: infrahub git-agent start --debug
    restart: unless-stopped
    depends_on:
      - infrahub-server
    environment:
      - "INFRAHUB_CONFIG=/source/development/infrahub.toml"
      - "INFRAHUB_ADDRESS=http://infrahub-server:8000"
      - "INFRAHUB_PRODUCTION=false"
      - "INFRAHUB_LOG_LEVEL=DEBUG"
      - "INFRAHUB_SDK_API_TOKEN=${INFRAHUB_SDK_API_TOKEN}"
      - "INFRAHUB_SDK_TIMEOUT=20"
      - "INFRAHUB_DB_TYPE=neo4j"
    volumes:
      - "git_data:/opt/infrahub/git"
      - "git_remote_data:/remote"
      - "../models:/tmp/models"
    tty: true

volumes:
  database_data:
  database_logs:
  git_data:
  git_remote_data:
  storage_data:
