query topology_info ($topology_name: String!) {
  InfraDevice(member_of_groups__name__value: $topology_name) {
    edges {
      node {
        name {
          value
        }
        interfaces {
          edges {
            node {
              id
              name {value}
              role {
                value
              }
              ... on InfraInterfaceL3 {
                ip_addresses {
                  edges {
                    node {
                      address {
                        value
                      }
                    }
                  }
                }
              }
              enabled { value}
              ... on InfraEndpoint {
                connected_endpoint {
                  node {
                    id
                    ... on InfraInterface {
                      name {
                        value
                      }
                      device {
                        node {
                          name {
                            value
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        device_type {
          node {
            name {
              value
            }
          }
        }
      }
    }
  }
}
