query oc_interfaces ($device_name: String!) {
  InfraDevice(name__value: $device_name) {
    edges {
      node {
        id
        interfaces {
          edges {
            node {
              name {
                value
              }
              description {
                value
              }
              enabled {
                value
              }
              ... on InfraInterfaceL3 {
                ip_addresses {
                  edges {
                    node {
                      address {
                        value
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
