query juniper_srx_config($device: String!) {
  InfraGenericDevice(name__value: $device) {
    edges {
      node {
        name {
          value
        }
        ... on SecurityFirewall {
          rules {
            edges {
              node {
                name {
                  value
                  }
                action {
                  value
                }
                log {
                  value
                }
                source_zone {
                  node {
                    name {
                      value
                    }
                  }
                }
                destination_zone {
                  node {
                    name {
                      value
                    }
                  }
                }
                source_address {
                  edges {
                    node {
                      name {
                        value
                      }
                    }
                  }
                }
                source_groups {
                  edges {
                    node {
                      name {
                        value
                      }
                    }
                  }
                }
                destination_address {
                  edges {
                    node {
                      name {
                        value
                      }
                    }
                  }
                }
                destination_groups {
                  edges {
                    node {
                      name {
                        value
                      }
                    }
                  }
                }
                destination_services {
                  edges {
                    node {
                      name {
                        value
                      }
                    }
                  }
                }
                destination_service_groups {
                  edges {
                    node {
                      name {
                        value
                      }
                    }
                  }
                }
              }
            }
          }
        }
	interfaces {
          edges {
            node {
              __typename
              name {
                value
              }
              role {
                value
              }
              ... on InfraInterfaceL3 {
                ip_addresses {
                  edges {
                    node {
                      address {
                        value
                      }
                    }
                  }
                }
              }
              ... on SecurityFirewallInterface {
                security_zone {
                  node {
                    name {
                      value
                    }
                  }
                }
                ip_addresses {
                  edges {
                    node {
                      address {
                        value
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  SecurityGenericAddress {
    edges {
      node {
        __typename
        name {
          value
        }
        ... on SecurityFQDN {
          fqdn {
            value
          }
        }
        ... on SecurityIPAddress {
          address {
            value
          }
        }
        ... on SecurityPrefix {
          prefix {
            value
          }
        }
      }
    }
  }
  SecurityGenericAddressGroup {
    edges {
      node {
        name {
          value
        }
        ... on SecurityAddressGroup {
          addresses {
            edges {
              node {
                name {
                  value
                }
              }
            }
          }
        }
      }
    }
  }
  SecurityService {
    edges {
      node {
        name {
          value
        }
        ip_protocol {
          node {
            name {
              value
            }
          }
        }
        port {
          value
        }
      }
    }
  }
  SecurityServiceGroup {
    edges {
      node {
        name {
          value
        }
        services {
          edges {
            node {
              name {
                value
              }
            }
          }
        }
      }
    }
  }
}
