---
- name: Fetch and Push Configuration to Arista Devices
  hosts: role_leaf,role_spine
  gather_facts: false
  vars:
    config_url: "http://localhost:8000/api/rfile/device_startup?device={{ inventory_hostname }}"
    local_config_path: "/tmp/{{ inventory_hostname }}.conf"

  tasks:
    - name: Fetch configuration from Infrahub
      ansible.builtin.get_url:
        url: "{{ config_url }}"
        dest: "{{ local_config_path }}"
      delegate_to: localhost

    - name: Push configuration to device
      arista.eos.eos_config:
        src: "{{ local_config_path }}"
      when: inventory_hostname in groups['platform_eos']
